version: '3.8'

services:
  ecoanalyzer:
    build: .
    container_name: ecoanalyzer-web
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-ecoanalyzer_secret_key_2025}
      - PORT=8081
      - PYTHONUNBUFFERED=1
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ecoanalyzer-network

networks:
  ecoanalyzer-network:
    driver: bridge

volumes:
  database:
  logs:
